version: '3.8'

services:

  hallel-api:
    image: thiagoramon/hallel-api:latest
    container_name: hallel-api-container
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - /etc/hallel-api/prod.env

    volumes:
      - /etc/hallel-api/crypto-avatar.json:/app/crypto-avatar.json
      - /etc/hallel-api/google-services.json:/app/google-services.json
      - /etc/hallel-api/hallel-messaging-firebase.json:/app/hallel-messaging-firebase.json

    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/hallel-api/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - hallel-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data: