version: '3.8'

services:
  hallel-api:
    # O nome da sua imagem no Docker Hub (ex: seunome/hallel-api)
    image: thiagoramon/hallel-api:latest
    container_name: hallel-api-container
    restart: always
    ports:
      # Mapeia a porta 8080 do servidor para a porta 8080 do contêiner
      - "8080:8080"
    # Carrega as variáveis de ambiente do arquivo .env no mesmo diretório
    env_file:
      - /etc/hallel-api/prod.env
    volumes:
      # Mapeia o arquivo do servidor (host) para dentro do contêiner
      - /etc/hallel-api/crypto-avatar.json:/app/crypto-avatar.json
      - /etc/hallel-api/google-services.json:/app/google-services.json
      - /etc/hallel-api/hallel-messaging-firebase.json:/app/hallel-messaging-firebase.json