#
#spring:
#  datasource:
#    url: jdbc:postgresql://hallel-app-db.cd66oaioym2y.us-east-2.rds.amazonaws.com:5432/hallel-db
#    username: halleladmin
#    password: Nowayout42#
#
#
#mercadopago:
#  access:
#    token: APP_USR-4555467526956218-082700-3a593e9193068d796699857780c741ce-2640484802
#  notification:
#    url: mercadopago.notification.url=${MERCADOPAGO_NOTIFICATION_URL}
