security:
  jwt:
    token:
      expire-length: 2592000000
      expire-coordenador-length: 86400000
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: hallel-api
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/hallel-db
    locations: classpath:db/migration
server:
  port: 8080
springdoc:
  api-docs:
    path: "/hallel-docs"
  swagger-ui:
    path: "/hallel-docs-ui"
    operations-sorter: method