MAIL_PASSWORD: uvbylzgyrbasdvte
MAIL_USERNAME: miguelimabr10@gmail.com
MERCADOPAGO_NOTIFICATION_URL: "https://comunidadecatolicahallel.com.br/public/payments/webhooks/mercadopago"
PEPPER_SECRET: 0b5c1b6a6f0e9f1e1b2c3d4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e
FIREBASE_FCM_TOKEN: AIzaSyB-ym4UH0PQahpZM9XzrrqCeQsJwnJdIos
MERCADOPAGO_ACCESS_TOKEN: APP_USR-4555467526956218-082700-3a593e9193068d796699857780c741ce-2640484802
JWT_SECRET: ZGFkNzMzYmMxODgxNmM5MGIxYjYwYzdlMmQ2YmFhOWYxMGU0YmMyY2JjYjdiM2U2NDk4MDUzYmY0ODBjN2U0MQ
NGROK_URL: https://8d0e25a1e19f.ngrok-free.app

server:
  port: 8080

security:
  password:
    pepper: ${PEPPER_SECRET}
  jwt:
    secret: ${JWT_SECRET}
    token:
      expire-length: 2592000000
      expire-coordenador-length: 86400000
firebase:
  messaging:
    fcm:
      token: ${FIREBASE_FCM_TOKEN}
      url: https://fcm.googleapis.com/v1/projects/hallel-messaging/messages:send
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  cloud:
    gcp:
      storage:
        bucket: hallel-bucket
  task:
    scheduling:
      cron: 0 00 * * * ?
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
  application:
    name: hallel-api
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true

cors:
  origin-patterns: http://localhost:5173,http://localhost:3000,https://comunidadecatolicahallel.com.br


mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN}
  notification:
    url: ${NGROK_URL}/public/payments/webhooks/mercadopago