# Todas as configurações e segredos serão injetados como variáveis de ambiente no deploy
spring:
  flyway:
    ignore-migration-patterns: V49
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

security:
  password:
    pepper: ${PEPPER_SECRET}
  jwt:
    token:
      expire-length: 2592000000 # Valor para produção
      expire-coordenador-length: 2592000000

firebase:
  messaging:
    fcm:
      token: ${FIREBASE_FCM_TOKEN}
      url: https://fcm.googleapis.com/v1/projects/hallel-messaging/messages:send

mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN}
  notification:
    url: ${MERCADOPAGO_NOTIFICATION_URL} # Esta será a URL pública da sua aplicação em produção