name: Build and Deploy Application to EC2

on:
  push:
    branches:
      - production # O deploy é acionado em push para a branch 'main'

jobs:
  build_and_deploy:
    name: 'Build and Deploy to Production EC2'
    runs-on: ubuntu-latest

    # Define que este job será executado no contexto do ambiente 'production'
    environment:
      name: production
      url: https://api.comunidadecatolicahallel.com.br

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: thiagoramon/hallel-api:latest

      - name: Generate prod.env file
        run: |
          tee crypto-avatar.json > /dev/null <<'EOF'
          ${{ secrets.CRYPTO_AVATAR_JSON }}
          EOF

          tee google-services.json > /dev/null <<'EOF'
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

          tee hallel-messaging-firebase.json > /dev/null <<'EOF'
          ${{ secrets.HALLEL_MESSAGING_FIREBASE_JSON }}
          EOF
          tee prod.env > /dev/null <<'EOF'
          SPRING_PROFILES_ACTIVE=prod
          SPRING_DATASOURCE_URL=jdbc:postgresql://${{ vars.DB_URL }}/hallel_db
          SPRING_DATASOURCE_USERNAME=${{ vars.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
          SPRING_MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          PEPPER_SECRET=${{ secrets.PEPPER_SECRET }}
          FIREBASE_FCM_TOKEN=${{ secrets.FIREBASE_FCM_TOKEN }}
          MERCADOPAGO_ACCESS_TOKEN=${{ secrets.MERCADOPAGO_ACCESS_TOKEN }}
          MERCADOPAGO_NOTIFICATION_URL=${{ secrets.MERCADOPAGO_NOTIFICATION_URL }}
          GCP_CREDENTIALS_PATH=/app/crypto-avatar.json
          EOF
          

      - name: Copia o docker-compose.yml para o servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSWORD }}
          source: "docker-compose.yml,prod.env"
          target: "/home/ec2-user/hallel-api"

      - name: Debug Secrets and Variables
        run: |
          echo "SERVER_IP is set: ${{ vars.SERVER_IP != '' }}"
          echo "DB_URL is set: ${{ vars.DB_URL != '' }}"
          echo "DB_USERNAME is set: ${{ vars.DB_USERNAME != '' }}"
          echo "DB_PASSWORD secret is set: ${{ secrets.DB_PASSWORD != '' }}"
          echo "EC2_SSH_PRIVATE_KEY secret is set: ${{ secrets.EC2_SSH_PRIVATE_KEY != '' }}"
          echo "MAIL_USERNAME secret is set: ${{ secrets.MAIL_USERNAME != '' }}"    

      - name: SSH, Configure and Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSWORD }}
          script: |
            mkdir -p /home/ec2-user/hallel-api
            sudo mkdir -p /etc/hallel-api
            
            sudo mv /home/ec2-user/hallel-api/prod.env /etc/hallel-api/prod.env
            sudo mv /home/ec2-user/hallel-api/crypto-avatar.json /etc/hallel-api/crypto-avatar.json
            sudo mv /home/ec2-user/hallel-api/google-services.json /etc/hallel-api/google-services.json
            sudo mv /home/ec2-user/hallel-api/hallel-messaging-firebase.json /etc/hallel-api/hallel-messaging-firebase.json

            cd /home/ec2-user/hallel-api
            docker-compose pull
            docker-compose up -d
